-- Cashflow forecasting upgrade (Tradify-inspired but more powerful)

create table if not exists cashflow_events (
  id bigint generated by default as identity primary key,
  project_id bigint,
  type text check (type in ('in','out')),
  category text,
  description text,
  amount numeric,
  due_date date,
  status text default 'forecast', -- forecast | committed | paid
  source text, -- invoice | labour | po | manual
  source_id bigint,
  created_at timestamp default now()
);

create index on cashflow_events(project_id);
create index on cashflow_events(due_date);

-- View for weekly rollup
create or replace view cashflow_weekly as
select
  project_id,
  date_trunc('week', due_date) as week,
  sum(case when type='in' then amount else 0 end) as cash_in,
  sum(case when type='out' then amount else 0 end) as cash_out
from cashflow_events
group by project_id, week;
